language: cpp
before_install:
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:boost-latest/ppa
  - sudo add-apt-repository --yes ppa:libreoffice/ppa 
  - sudo sh -c 'echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" >> /etc/apt/sources.list'
  - sudo apt-get update
install:
  - sudo apt-get install --yes --force-yes g++-4.8 g++-4.9 clang-3.7 libboost1.55-all-dev cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - sudo pip install cpp-coveralls pyyaml
  - echo COMPILER="${COMPILER}"
env:
  matrix:
    - CONF=Debug   COMPILER=g++-4.9     COVERAGE=0 USE_BOOST_STRING_VIEW=0 USE_BOOST_REGEX=0 PUBLISH_DOCS=0
    - CONF=Debug   COMPILER=g++-4.9     COVERAGE=0 USE_BOOST_STRING_VIEW=1 USE_BOOST_REGEX=0 PUBLISH_DOCS=0
    - CONF=Release COMPILER=g++-4.9     COVERAGE=0 USE_BOOST_STRING_VIEW=0 USE_BOOST_REGEX=0 PUBLISH_DOCS=1
    - CONF=Release COMPILER=g++-4.9     COVERAGE=0 USE_BOOST_STRING_VIEW=0 USE_BOOST_REGEX=1 PUBLISH_DOCS=0
    - CONF=Release COMPILER=g++-4.9     COVERAGE=0 USE_BOOST_STRING_VIEW=1 USE_BOOST_REGEX=0 PUBLISH_DOCS=0
    - CONF=Release COMPILER=g++-4.9     COVERAGE=0 USE_BOOST_STRING_VIEW=1 USE_BOOST_REGEX=1 PUBLISH_DOCS=0
    - CONF=Release COMPILER=g++-4.8     COVERAGE=1 USE_BOOST_STRING_VIEW=0 USE_BOOST_REGEX=1 PUBLISH_DOCS=0
    - CONF=Release COMPILER=g++-4.8     COVERAGE=0 USE_BOOST_STRING_VIEW=0 USE_BOOST_REGEX=1 PUBLISH_DOCS=0
    - CONF=Release COMPILER=g++-4.8     COVERAGE=0 USE_BOOST_STRING_VIEW=1 USE_BOOST_REGEX=1 PUBLISH_DOCS=0
    - CONF=Release COMPILER=clang++-3.7 COVERAGE=0 USE_BOOST_STRING_VIEW=0 USE_BOOST_REGEX=0 PUBLISH_DOCS=0
    - CONF=Release COMPILER=clang++-3.7 COVERAGE=0 USE_BOOST_STRING_VIEW=0 USE_BOOST_REGEX=1 PUBLISH_DOCS=0
    - CONF=Release COMPILER=clang++-3.7 COVERAGE=0 USE_BOOST_STRING_VIEW=1 USE_BOOST_REGEX=0 PUBLISH_DOCS=0
    - CONF=Release COMPILER=clang++-3.7 COVERAGE=0 USE_BOOST_STRING_VIEW=1 USE_BOOST_REGEX=1 PUBLISH_DOCS=0
script:
  - ${COMPILER} --version
  - cmake -DCMAKE_CXX_COMPILER=${COMPILER}
          -DCMAKE_BUILD_TYPE=${CONF}
          -DUSE_BOOST_REGEX=${USE_BOOST_REGEX}
          -DUSE_BOOST_STRING_VIEW=${USE_BOOST_STRING_VIEW}
          -DCOVERAGE=${COVERAGE}
  - make VERBOSE=1
  - ./jsonv-tests
  - if [[ ${COVERAGE} == 1 ]]; then ./config/upload-coverage; fi
after_success:
  - if [[ ${PUBLISH_DOCS} == 0 ]]; then echo "Skipping documentation publishing."; exit 0; fi
  - sudo apt-get install --yes doxygen graphviz
  - openssl aes-256-cbc
    -K $encrypted_da53dd2710a4_key
    -iv $encrypted_da53dd2710a4_iv
    -in  config/travisci_rsa.enc
    -out config/travisci_rsa
    -d
  - chmod 0600 config/travisci_rsa
  - cp config/travisci_rsa ~/.ssh/id_rsa
  - ./config/publish-doxygen
