language: cpp
before_install:
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository --yes ppa:boost-latest/ppa
  - sudo sh -c 'echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" >> /etc/apt/sources.list'
  - sudo apt-get update
install:
  - sudo apt-get install --yes g++-4.8 clang-3.3 libboost1.55-all-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
env:
  matrix:
    - CONF=debug COMPILER=g++     STRING_REF_NAME=jsonv USE_BOOST_STRING_REF=0
    - CONF=debug COMPILER=g++     STRING_REF_NAME=boost USE_BOOST_STRING_REF=1
    - CONF=debug COMPILER=clang++ STRING_REF_NAME=jsonv USE_BOOST_STRING_REF=0
    - CONF=debug COMPILER=clang++ STRING_REF_NAME=boost USE_BOOST_STRING_REF=1
script:
  - make CONF=${CONF} BUILD_DIR=build/${CONF}-${STRING_REF_NAME}-string-ref VERBOSE=1 CXX_COMPILER=${COMPILER} USE_BOOST_REGEX=1 USE_BOOST_STRING_REF=${USE_BOOST_STRING_REF}
after_success:
  - sudo apt-get install --yes doxygen graphviz
  - openssl aes-256-cbc
    -K $encrypted_da53dd2710a4_key
    -iv $encrypted_da53dd2710a4_iv
    -in  config/travisci_rsa.enc
    -out config/travisci_rsa
    -d
  - chmod 0600 config/travisci_rsa
  - cp config/travisci_rsa ~/.ssh/id_rsa
  - ./config/publish-doxygen
