version: 1.1.{build}
environment:
  BOOST_ROOT: C:\Libraries\boost
  BOOST_LIBDIR: C:\Libraries\boost\stage\lib
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
init:
  - cmd: cmake --version
  - cmd: msbuild /version
clone_folder: C:\projects\json-voorhees
before_build:
  - cmd: cd C:\projects\json-voorhees
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 14"       -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..
  - cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 14 Win64" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..
build:
  project: C:\projects\json-voorhees\build\json-voorhees.sln
test_script:
  - cmd: C:\projects\json-voorhees\build\jsonv-tests
