version: 1.1.{build}
os: Visual Studio 2015
environment:
  BOOST_ROOT: C:\Libraries\boost_1_59_0
  BOOST_LIBDIR: C:\Libraries\boost_1_59_0\stage\lib
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
install:
  - cmd: cmake --help
  #- cmd: msbuild /version
clone_folder: C:\projects\json-voorhees
before_build:
  - cmd: cd C:\projects\json-voorhees\vs2015
  - cmd: nuget restore
  #- cmd: cd C:\projects\json-voorhees
  #- cmd: md build
  #- cmd: cd build
  #- cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 14"       -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..
  #- cmd: if "%platform%"=="x64"   cmake -G "Visual Studio 14 Win64" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..
build:
  project: C:\projects\json-voorhees\vs2015\JsonVoorhees.sln
  #project: C:\projects\json-voorhees\build\json-voorhees.sln
test_script:
  #- cmd: C:\projects\json-voorhees\build\jsonv-tests
